2025-10-12 23:41:01,616 INFO Starting analysis master script
2025-10-12 23:41:01,617 INFO Running group_advantage pipeline
2025-10-12 23:41:01,617 INFO Timing: group_advantage.raw_data_cleaning
2025-10-12 23:41:01,617 INFO Running R script /Users/xehu/Desktop/task-mapping/analysis/analysis_group_advantage/raw_data_cleaning.R
2025-10-12 23:41:01,617 INFO Running command: /usr/local/bin/Rscript -e set.seed(as.integer(Sys.getenv('ANALYSIS_SEED', '19104'))); source('raw_data_cleaning.R') (cwd=/Users/xehu/Desktop/task-mapping/analysis/analysis_group_advantage)
2025-10-12 23:41:01,737 INFO Error in source("raw_data_cleaning.R") :
2025-10-12 23:41:01,737 INFO   raw_data_cleaning.R:88:61: unexpected symbol
2025-10-12 23:41:01,737 INFO 87:     if ("_id" %in% names(data)) {
2025-10-12 23:41:01,737 INFO 88:     data <- data |> dplyr::rename(!!rlang::sym(primary) := _id
2025-10-12 23:41:01,737 INFO                                                                 ^
2025-10-12 23:41:01,737 INFO Execution halted
2025-10-12 23:41:01,743 ERROR Error during group_advantage.raw_data_cleaning after 0.126 sec
Traceback (most recent call last):
  File "/Users/xehu/Desktop/task-mapping/analysis/run_master.py", line 414, in time_callable
    res = func()
  File "/Users/xehu/Desktop/task-mapping/analysis/run_master.py", line 552, in <lambda>
    results.append(time_callable('group_advantage.raw_data_cleaning', lambda: run_r_script(r_script_clean)))
                                                                              ~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/Users/xehu/Desktop/task-mapping/analysis/run_master.py", line 355, in run_r_script
    raise RuntimeError(f'R script failed (exit {rc}): {r_path}')
RuntimeError: R script failed (exit 1): /Users/xehu/Desktop/task-mapping/analysis/analysis_group_advantage/raw_data_cleaning.R
